### ISSUE TITLE
Patch is not working it seems 

### ISSUE THREAD

**Issue by heeropunjabi** [rebrowser/rebrowser-patches#6] opened 2024-08-19 20:35 UTC
Please try these steps 
1. package.json
<img width="760" alt="Screenshot 2024-08-20 at 1 58 54 AM" src="https://github.com/user-attachments/assets/f4960ac5-a1c9-4322-96ed-f9218a220ef3">

2. codebase 
<img width="1192" alt="Screenshot 2024-08-20 at 2 00 13 AM" src="https://github.com/user-attachments/assets/e56d370e-6064-48aa-b390-a3a46fee7b3a">

3. patching things
![2024-08-20_02-03](https://github.com/user-attachments/assets/740dad4f-0753-4a66-9f62-c389d3e786b6)

4. Still not working 
<img width="1170" alt="Screenshot 2024-08-20 at 2 04 34 AM" src="https://github.com/user-attachments/assets/1ef98034-4e4f-48b4-b9f4-d43c1647d486">

**Adding Code for quick reproduce.**

**js code** 
`process.env.REBROWSER_PATCHES_RUNTIME_FIX_MODE = 'alwaysIsolated'
process.env.REBROWSER_PATCHES_DEBUG = '1'

const puppeteer = require('puppeteer-extra')

const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

;(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
        ignoreDefaultArgs: ['--enable-automation'],
    })
    

    const page = await browser.newPage()
    await page.goto('https://www.browserscan.net/bot-detection')
    
    

//   await browser.close()
})()

`

**Comment by nwebson** [comment] 2024-08-19 20:40
Could you try to use it without puppeteer-extra and stealth plugin?
Try just 
```
const puppeteer = require('puppeteer-core')
```

**Comment by heeropunjabi** [comment] 2024-08-20 06:35
@nwebson still the same issue with the puppetter-core also :(
<img width="929" alt="image" src="https://github.com/user-attachments/assets/bdcaca09-1587-4076-a274-f3f9f0a39bdc">

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/16e84e7d-f943-42a4-8997-0752e45098a1">

**Comment by nwebson** [comment] 2024-08-20 16:48
@heeropunjabi can you see debug messaged from rebrowser-patches in your console during the run? You should see it as you have debug flag enabled. If you don't see it, then the patch wasn't applied.

**Comment by zfcsoftware** [comment] 2024-08-20 19:02
> @heeropunjabi can you see debug messaged from rebrowser-patches in your console during the run? You should see it as you have debug flag enabled. If you don't see it, then the patch wasn't applied.

I'm facing the same problem.

https://github.com/user-attachments/assets/461f1355-5f25-40be-9910-399c58727b78

**Comment by nwebson** [comment] 2024-08-20 23:03
@zfcsoftware very nice video and code, highly appreciated. I will try to replicate this with your code today/tomorrow and will get back with some solution.

**Comment by nwebson** [comment] 2024-08-22 20:35
Hey there! 
I found the issue, your code was working without the patch because you were using `require` (cjs) instead of `import` (esm) and it wasn't supported by the patch.

I just released a new version of the patch that includes cjs files, too. So, you can remove node_modules folder, run npm install, then apply patch again (use `npx rebrowser-patches@latest patch`). And then you should see some debug messages in the console. If you don't see it, it's not applied again, please check everything.

I tried your code @zfcsoftware, now with new version of the patches it works fine and I can see debug messages from the patch, but I'm getting 0.1 score. The reason is that you're using pptr Chrome (testing channel of Chromium) and also their launch commands. I've used your code but instead, I opened vanilla Chrome with `--remote-debugging-port=5555` switch, and then changed your code to 
```
const browser = await puppeteer.connect({
    browserURL: 'http://127.0.0.1:5555'
});
```
So, with this approach and applied patches, I'm getting 0.7 score instead of 0.1. I also tried your code with new patch applied  with [remote browser](https://rebrowser.net), and I've got 0.9 score. So, patch itself won't magically fix the score, you need to take care of other things as well.

**Comment by zfcsoftware** [comment] 2024-08-22 22:17
> Hey there! I found the issue, your code was working without the patch because you were using `require` (cjs) instead of `import` (esm) and it wasn't supported by the patch.
> 
> I just released a new version of the patch that includes cjs files, too. So, you can remove node_modules folder, run npm install, then apply patch again (use `npx rebrowser-patches@latest patch`). And then you should see some debug messages in the console. If you don't see it, it's not applied again, please check everything.
> 
> I tried your code @zfcsoftware, now with new version of the patches it works fine and I can see debug messages from the patch, but I'm getting 0.1 score. The reason is that you're using pptr Chrome (testing channel of Chromium) and also their launch commands. I've used your code but instead, I opened vanilla Chrome with `--remote-debugging-port=5555` switch, and then changed your code to
> 
> ```
> const browser = await puppeteer.connect({
>     browserURL: 'http://127.0.0.1:5555'
> });
> ```
> 
> So, with this approach and applied patches, I'm getting 0.7 score instead of 0.1. I also tried your code with new patch applied with [remote browser](https://rebrowser.net), and I've got 0.9 score. So, patch itself won't magically fix the score, you need to take care of other things as well.


Hello, thanks for the update. The patch works fine. I figured out why Recaptcha v3 was giving a low score.
The first problem is launching Chromium. If it is launched with Puppeteer's native path it scores at most 0.7. If it is launched with chrome-launcher it scores 0.9. That was the first problem.

2. The problem is mouse movements. If you run the test and do nothing on the page, it gives you a score of 0.3. But if you move the mouse and scroll, you get a score of 0.9.

Although I tried libraries like ghost-cursor, I couldn't simulate mouse movements. But this is not a problem with the library. It's a problem with mouse movements. I suggest you add the following sample code and information about mouse movements to the readme file. 


https://github.com/user-attachments/assets/415251df-2217-4d86-833f-2f36e0e66ee5

```
const test = require('node:test');
const assert = require('node:assert');
const puppeteer = require('puppeteer-core');
const vanillaPuppeteer = require('puppeteer');
process.env.REBROWSER_PATCHES_RUNTIME_FIX_MODE = "alwaysIsolated"


test("Check Recaptcha V3 Score", async (t) => {
    const { launch, Launcher } = await import("chrome-launcher")
    const chrome = await launch({
        chromeFlags: Launcher.defaultFlags()
    });
    const data = await fetch(`http://127.0.0.1:${chrome.port}/json/version`).then(r => r.json()).then(r => [r["User-Agent"], r["webSocketDebuggerUrl"]])
    const browser = await puppeteer.connect({
        browserWSEndpoint: data[1]
    });
    const [page] = await browser.pages();
    await page.goto("https://antcpt.com/score_detector/");
    await new Promise(r => setTimeout(r, 3000));
    const score = await page.evaluate(() => {
        return document.querySelector('big').textContent.replace(/[^0-9.]/g, '')
    })
    await browser.close();
    assert.strictEqual(Number(score) >= 0.7, true, "Recaptcha V3 Score should be 0.9. Score Result: " + score);
});


test("Puppeteer Chromium Check Recaptcha V3 Score", async (t) => {
    const browser = await puppeteer.launch({
        executablePath: vanillaPuppeteer.executablePath(),
        headless: false,
        args: [
            "--disable-blink-features=AutomationControlled"
        ]
    });
    const [page] = await browser.pages();
    await page.goto("https://antcpt.com/score_detector/");
    await new Promise(r => setTimeout(r, 3000));
    const score = await page.evaluate(() => {
        return document.querySelector('big').textContent.replace(/[^0-9.]/g, '')
    })
    await browser.close();
    assert.strictEqual(Number(score) >= 0.7, true, "Puppeteer Chromium Recaptcha V3 Score should be 0.9. Score Result: " + score);
})
```

package.json

```
{
  "name": "patch",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "chrome-launcher": "^1.1.2",
    "puppeteer": "^23.1.1",
    "puppeteer-core": "22.15.0"
  }
}

```

**Comment by nwebson** [comment] 2024-08-30 16:45
I'm closing this issue as irrelevant to the project.
I will consider adding some mouse-related stuff, thanks for the idea.

**Closed by nwebson** 2024-08-30 16:45 UTC
